{application,openai,
             [{description,"Erlang client for OpenAI API with dynamic client generation"},
              {vsn,"0.1.0"},
              {registered,[openai_sup,openai_generator_sup,openai_clients_sup,
                           openai_generator,openai_rate_limiter,
                           openai_config]},
              {applications,[kernel,stdlib,inets,ssl,jsx]},
              {mod,{openai_app,[]}},
              {env,[{auto_start_groups,[chat,completions,embeddings]},
                    {output_dir,"/tmp/openai-erlang"}]},
              {licenses,["MIT"]},
              {maintainers,["Arthur Colle"]},
              {links,[{"GitHub","https://github.com/arthurcolle/agents.erl"},
                      {"Documentation","https://agents.erl.sh"}]},
              {modules,[anthropic_api_structure,anthropic_client,
                        anthropic_client_template,openai_api_structure,
                        openai_app,openai_chat,openai_client_template,
                        openai_clients_sup,openai_completions,openai_config,
                        openai_embeddings,openai_generator,
                        openai_generator_sup,openai_rate_limiter,
                        openai_sup]}]}.
